### ISSUE TITLE
mingo@6.2.2 breaks CommonJS requires of files inside package

### ISSUE THREAD

**Issue by ericyhwang** [kofrasa/mingo#295]
mingo@6.2.2 (874ab58ee60aa6b2d3c4f95cce1f819d047a4925) introduced a likely-accidental breaking change to mingo's published library structure, moving output JS files underneath `lib/`.

This means the CommonJS `require` examples from the README using child files, which worked in mingo@6.2.1, no longer work in mingo@6.2.2:
```
> const core = require("mingo/core");
Uncaught Error: Cannot find module 'mingo/core'
```

It also roughly doubles the package size, since there are now two copies of the JS output, under `lib/` and `es/`.

Would you be ok with unpublishing or deprecating 6.2.2 + reverting until the breaking change can be addressed?

If you haven't seen it already, the Node docs have advice on writing packages that can be natively used from both CommonJS modules and ES Modules environments. I haven't tried it myself, but it seems to be thorough.
https://nodejs.org/docs/latest-v12.x/api/packages.html#packages_writing_dual_packages_while_avoiding_or_minimizing_hazards

**Comment by kofrasa** [comment]
Sorry for the breaking change. I tested both using `require` for CommonJS module and `import` for ES6 modules. Perhaps there was something amiss there. I will deprecate this version for now.

**Comment by ericyhwang** [comment]
> I tested both using `require` for CommonJS module and `import` for ES6 modules. Perhaps there was something amiss there.

It works fine if requiring just the root package itself, because the `main` field in package.json maps it to lib/index.js. It only breaks when requiring a specific file inside the package, since that's still based on the actual filesystem paths.
```
// OK
require('mingo');
// Not OK
require('mingo/core');
require('mingo/init/system');
```

**Comment by kofrasa** [comment]
Gotcha. I have verified the bug. Deprecating version `6.2.2` for now.

**Comment by pubkey** [comment]
I still have the problem when building with typescript. (Non-typescript build works.)

![broken-types](https://user-images.githubusercontent.com/8926560/211003516-8d5f5584-b73b-4a99-83b9-314e66fe9652.png)

**Comment by kofrasa** [comment]
Seemed to build fine from the link. Are you still seeing issues?

**Comment by pubkey** [comment]
You have to leave the tab open for a while until the npm deps are installed in the background. Then the editor will show the import errors and that it is not able to find the types.
I am investigating the root problem but atm. I have no clue. I tried modifying severeral parts in the package.json but that did not help.

**Comment by pubkey** [comment]
I have the same error when processing the types with plain typescript in the cli, without an editor.
See https://github.com/pubkey/rxdb/actions/runs/3855130020/jobs/6569861677

**Comment by pubkey** [comment]
Settings `"moduleResolution": "NodeNext"` in the tsconfig seems to resolve the problem.
But strange that this is required to make it work.

**Comment by kofrasa** [comment]
I wasn't familiar with that value for "moduleResolution" but it seems to be what is required according to https://www.typescriptlang.org/tsconfig#moduleResolution.

**Comment by kofrasa** [comment]
> You have to leave the tab open for a while until the npm deps are installed in the background. Then the editor will show the import errors and that it is not able to find the types.
> 
> ![broken-type-2](https://user-images.githubusercontent.com/8926560/211007943-7eea0f1a-763b-4be0-b395-8edb855cfec5.png)
> 
> I am investigating the root problem but atm. I have no clue. I tried modifying severeral parts in the package.json but that did not help.

I see this now.

**Comment by kofrasa** [comment]
I only see a single `package.json` in `rxjs`. The files are actually pretty similar but I am missing the `./package.json` in the export. Will publish a version with that included and the changes proposed.

**Comment by pubkey** [comment]
There is only a single package.json in the rxjs repo. But in the release package, there are different package.json files, one for each submodule. For example `rxjs/ajax/package.json`.
I cannot hotlink it on npm, but you can see it on the file explorer here https://www.npmjs.com/package/rxjs?activeTab=explore

**Comment by kofrasa** [comment]
I see what you mean. That seems to work for a flat structure. I may have to generate that for each nested operator module defined in this project.

For example it may work for `mingo/core` but would it work for `mingo/operators/pipeline`?

Do we create the entire folder structure with each level having their own `package.json`?

**Comment by kofrasa** [comment]
You are right. It looks like that's how it has to be. See https://www.npmjs.com/package/rxdb?activeTab=explore.

I modelled `6.2.3` exports after `rxdb` which seems to do just that.

**Comment by pubkey** [comment]
> Do we create the entire folder structure with each level having their own package.json?

No. When `sideEffects: false` is set, the bundler will automatically tree-shake the non-used code. So you only need to create package.json files for the main submodules, not for each single operator.

**Comment by pubkey** [comment]
Setting `sideEffects: false` on the root package.json does not seem correct.
For example the code fills up the operators in the init here https://github.com/kofrasa/mingo/blob/master/src/init/system.ts which is a side effect because it directly runs on import and mutates a "global" state.

**Comment by pubkey** [comment]
@kofrasa  I am working on a PR.
